fix minor formatting and grammar issues in docs
stitchfix/hamilton pull request #102
Opened 2022-03-27 21:26 UTC by jameslamb

Fixes some minor formatting and grammar issues I noticed while reading through this project's documentation.

## Changes

- fixes formatting in `.md` files
- fixes small grammar issues

## Testing

None

## Notes

None

## Checklist

- [x] PR has an informative and human-readable title (this will be pulled into the release notes)
- [x] Changes are limited to a single goal (no scope creep)
- [x] Code can be automatically merged (no conflicts)
- [x] Code passed the pre-commit check & code is left cleaner/nicer than when first encountered.
- [ ] Passes all existing automated tests
- [x] Any _change_ in functionality is tested
- [x] New functions are documented (with a description, list of inputs, and expected output)
- [x] Placeholder code is flagged / future TODOs are captured in comments
- [x] Project documentation has been updated if adding/changing functionality.
- [ ] Reviewers requested with the [Reviewers tool](https://help.github.com/articles/requesting-a-pull-request-review/) :arrow_right:

## Testing checklist

### Python - local testing

- [ ] python 3.6
- [ ] python 3.7

2022-03-27 21:27 UTC, jameslamb commented on README.md
> +For the backstory on Hamilton we invite you to watch a roughly-9 minute lightning talk on it that we gave at the apply conference:
`~` is a special markdown character used for strike-through text: https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#styling-text

2022-03-27 21:30 UTC, jameslamb commented on basics.md
> +#### modules: ModuleType
based on the formatting of other sections at https://github.com/stitchfix/hamilton/blob/49f11ede9a79478f31b8ded2673ec0f977033562/basics.md, I think this `*` was unintended.

<img width="1258" alt="Screen Shot 2022-03-27 at 4 30 04 PM" src="https://user-images.githubusercontent.com/7608904/160301842-e429f7e2-6a2b-4fe1-afcb-d7161c2fce17.png">

2022-03-27 21:31 UTC, jameslamb commented on decorators.md
> +The `@does` decorator is currently limited to just allow functions that consist only of one argument, a generic `**kwargs`.
Markdown renderers recognize `**` as "bold": https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#styling-text

But I think here the intention was to refer to the literal Python code `**kwargs`.

2022-03-29 01:59 UTC, elijahbenizzy commented
Nice finds! I think the only intentional one is the *modules :)

2022-03-30 13:51 UTC, jameslamb commented
> I think the only intentional one is the *modules

Ok, sure. Did you mean that you want a literal `*` at the beginning of that section, or that it was intended to be closed with another `*` to italicize it?

2022-03-30 16:32 UTC, elijahbenizzy requested changes

2022-03-31 00:19 UTC, skrawcz commented
> > I think the only intentional one is the *modules
> 
> Ok, sure. Did you mean that you want a literal `*` at the beginning of that section, or that it was intended to be closed with another `*` to italicize it?

We meant for it to be a literal `*` to match the parameter declaration.

2022-03-31 00:24 UTC, jameslamb commented on basics.md
> +#### modules: ModuleType
ahhh got it! Pushed https://github.com/stitchfix/hamilton/pull/102/commits/dc920431b2db796b6da86842349ed465ce621b30 adding it back, with escaping.

You can see how GitHub renders it on my branch.

https://github.com/jameslamb/hamilton/blob/docs-fixes/basics.md

<img width="1083" alt="Screen Shot 2022-03-30 at 7 23 38 PM" src="https://user-images.githubusercontent.com/7608904/160952024-022e1ae6-97d0-471e-9b1c-b54a5d303904.png">

2022-04-11 04:47 UTC, skrawcz approved these changes

2022-04-11 04:50 UTC, skrawcz commented
@jameslamb mind if I squash merge? I want to remove the merge commit - else I would do a rebase merge.

2022-04-11 04:56 UTC, merged