remove unused loggers
stitchfix/hamilton pull request #103
Opened 2022-03-27 22:08 UTC by jameslamb

Looking through this project's code today, I found several places where module-specific loggers are instantiated but never used.

This PR proposes removing them

## Changes

- removes import of `logging` and instantiation of unused loggers in docs, examples, and the package itself

## Testing

Ran the following to emulate CircleCI locally.

```shell
docker run \
   --rm \
    -v $(pwd):/usr/local/src \
    --workdir /usr/local/src \
   -it circleci/python:3.7 \
        /bin/bash
```

And then installed `hamilton` and ran its tests.

```shell
# install dependencies
sudo apt install graphviz
python -m venv venv || virtualenv venv
. venv/bin/activate
python --version
pip --version
pip install -r requirements-test.txt
pip install -r requirements.txt
pip install "dask[complete]"

# run tests
python -m pytest --cov=hamilton tests/
python -m pytest graph_adapter_tests/h_dask
```

## Notes

- removing unnecessary code from examples simplifies those examples and makes them more easier for new users to understand
- removing unnecessary imports and module-level instantiations reduces the time it takes to run `import hamilton`
- removing unused code reduces the time it takes to run static analyzers like `mypy` and `flake8`

Thanks for your time and consideration!

## Checklist

- [x] PR has an informative and human-readable title (this will be pulled into the release notes)
- [x] Changes are limited to a single goal (no scope creep)
- [x] Code can be automatically merged (no conflicts)
- [x] Code passed the pre-commit check & code is left cleaner/nicer than when first encountered.
- [ ] Passes all existing automated tests
- [x] Any _change_ in functionality is tested
- [x] New functions are documented (with a description, list of inputs, and expected output)
- [x] Placeholder code is flagged / future TODOs are captured in comments
- [x] Project documentation has been updated if adding/changing functionality.
- [ ] Reviewers requested with the [Reviewers tool](https://help.github.com/articles/requesting-a-pull-request-review/) :arrow_right:

## Testing checklist

### Python - local testing

- [ ] python 3.6
- [x] python 3.7

2022-03-29 02:00 UTC, elijahbenizzy approved these changes
Nice! Can't believe we had so much cruft...

2022-03-29 05:46 UTC, skrawcz requested changes
I think we want to keep the logging setup lines. Since they control logging and are the entry point to running things. Otherwise yeah, if we're not using the loggers we should remove them -- can always add them back when we have something to log.

2022-03-29 05:46 UTC, skrawcz commented on README.md
> -logging.basicConfig(stream=sys.stdout)
I believe I included this because I've seen people not know how to setup logging.  So I'm inclined to keep this line, but yeah, we don't need the logger  because we don't use it.

2022-03-29 05:46 UTC, skrawcz commented on examples/hello_world/my_script.py
> -logging.basicConfig(stream=sys.stdout)
ditto -- let's keep this.

2022-03-30 14:32 UTC, jameslamb commented on README.md
> -logging.basicConfig(stream=sys.stdout)
sure, can do! Restored in https://github.com/stitchfix/hamilton/pull/103/commits/85a1a82e81e3bcbdc12d9b127d8f61e1d022f292

2022-03-30 14:33 UTC, jameslamb commented on examples/hello_world/my_script.py
> -logging.basicConfig(stream=sys.stdout)
ok no prob, restored in https://github.com/stitchfix/hamilton/pull/103/commits/85a1a82e81e3bcbdc12d9b127d8f61e1d022f292

2022-04-11 04:52 UTC, skrawcz approved these changes

2022-04-11 04:52 UTC, skrawcz commented
@jameslamb apologies for the slowness -- I miss github notifications often :/

2022-04-11 04:55 UTC, merged

2022-04-11 13:31 UTC, jameslamb commented
ha no problem!