Data quality pandera
stitchfix/hamilton pull request #147
Opened 2022-07-03 00:05 UTC by elijahbenizzy

[Short description explaining the high-level reason for the pull request]

## Changes

-

## Testing

1.

## Notes

## Checklist

- [ ] PR has an informative and human-readable title (this will be pulled into the release notes)
- [ ] Changes are limited to a single goal (no scope creep)
- [ ] Code can be automatically merged (no conflicts)
- [ ] Code passed the pre-commit check & code is left cleaner/nicer than when first encountered.
- [ ] Passes all existing automated tests
- [ ] Any _change_ in functionality is tested
- [ ] New functions are documented (with a description, list of inputs, and expected output)
- [ ] Placeholder code is flagged / future TODOs are captured in comments
- [ ] Project documentation has been updated if adding/changing functionality.
- [ ] Reviewers requested with the [Reviewers tool](https://help.github.com/articles/requesting-a-pull-request-review/) :arrow_right:

## Testing checklist

### Python - local testing

- [ ] python 3.6
- [ ] python 3.7

2022-07-03 00:14 UTC, elijahbenizzy commented
Fairly basic pandera integration, but I actually like it quite a bit. Remaining before merge:

- [ ] Documentation
- [ ] Polishing of the conditional imports stuff
- [ ] Another pass at improving diagnostics/serializing pandera checks (might as well use the yaml stuff they have, although its clunky)

2022-07-03 03:52 UTC, skrawcz commented on hamilton/data_quality/default_validators.py
> +        return
This might be clearer?
```suggestion
    try:
        import pandera
    except ModuleNotFoundError:
        logger.info(f'Skipping import of pandera for pandera_validators. Run pip install hamilton[pandera] if needed.')
        return
    else:
        import pandera_validators
```

2022-07-03 03:56 UTC, skrawcz commented
Question: Could the default validators we have be implemented instead with Pandera, i.e. delegate to it? If so, then perhaps a capability to swap the default implementation would be useful?

2022-07-03 04:40 UTC, elijahbenizzy commented
> Question: Could the default validators we have be implemented instead with Pandera, i.e. delegate to it? If so, then perhaps a capability to swap the default implementation would be useful?
> 
> 

Yes they could -- made a note in the commute though. I guess we have to decide whether it's worth having multiple implementations? Or just reimplementing the default to reduce surface area.

2022-07-04 01:22 UTC, elijahbenizzy commented on hamilton/data_quality/default_validators.py
> +        return
Agreed, that is a little easier to read.

2022-07-05 05:10 UTC, skrawcz requested changes
I just want a couple of items to be added to the docs.

Also a circular import is a code smell. So I think putting that base class in base makes sense...

Otherwise man those class imports from modules look pretty 🤮 ... will clean them up when we reformat using black...

2022-07-05 05:10 UTC, skrawcz commented on hamilton/data_quality/default_validators.py
> +    AVAILABLE_DEFAULT_VALIDATORS.extend(pandera_validators.PANDERA_VALIDATORS)
is this white space off?

2022-07-05 05:10 UTC, skrawcz commented on data_quality.md
> +This is near-trivial to use. All you have to do is provide a pandera schema
We shouldn't say it's easy incase we make someone feel stupid. Suggestion : "This should not take you long to start using".

2022-07-05 05:10 UTC, skrawcz commented on data_quality.md
> +This is near-trivial to use. All you have to do is provide a pandera schema
Also link to what a pandera schema is -- and say something like (don't know what a pandera schema is, please read up on it here..)

2022-07-05 05:10 UTC, skrawcz commented on data_quality.md
> +You can also do schema checks on series, using the `pa.SeriesSchema` feature!
should provide an example here too. people want to copy & paste.

2022-07-05 15:30 UTC, elijahbenizzy commented on hamilton/data_quality/default_validators.py
> +    AVAILABLE_DEFAULT_VALIDATORS.extend(pandera_validators.PANDERA_VALIDATORS)
Weird its not showing up on mine

2022-07-05 18:13 UTC, skrawcz commented on data_quality.md
> +This is near-trivial to use. All you have to do is provide a pandera schema
Frustrated < Stupid IMO.

2022-07-05 18:14 UTC, skrawcz approved these changes

2022-07-05 23:15 UTC, skrawcz commented on hamilton/data_quality/default_validators.py
> +    AVAILABLE_DEFAULT_VALIDATORS.extend(pandera_validators.PANDERA_VALIDATORS)
You fixed it in a later commit.

2022-07-06 15:33 UTC, merged