Rough POC that we can do async without touching function graph
stitchfix/hamilton pull request #171
Opened 2022-08-06 23:40 UTC by elijahbenizzy

@stefan this is what I meant

Basically we pass the coroutine the entire way through.
When a function depends on other data, we create a coroutine that
awaits everything. Finally, we do a gather at the end.

I *think* this is optimal but will need to dig in a bit/look into
things.

Otherwise, nifty POC with *very* rough edges.

The biggest hack is that I'm using a cache to store coroutine values as python makes it very hard to access them. 
I think we can do better, but the point is we don't have to mess with execution.

[Short description explaining the high-level reason for the pull request]

## Changes

-

## Testing

1.

## Notes

## Checklist

- [ ] PR has an informative and human-readable title (this will be pulled into the release notes)
- [ ] Changes are limited to a single goal (no scope creep)
- [ ] Code can be automatically merged (no conflicts)
- [ ] Code passed the pre-commit check & code is left cleaner/nicer than when first encountered.
- [ ] Passes all existing automated tests
- [ ] Any _change_ in functionality is tested
- [ ] New functions are documented (with a description, list of inputs, and expected output)
- [ ] Placeholder code is flagged / future TODOs are captured in comments
- [ ] Project documentation has been updated if adding/changing functionality.
- [ ] Reviewers requested with the [Reviewers tool](https://help.github.com/articles/requesting-a-pull-request-review/) :arrow_right:

## Testing checklist

### Python - local testing

- [ ] python 3.6
- [ ] python 3.7

2022-08-06 23:51 UTC, skrawcz commented on hamilton/driver.py
> +            fn_kwargs = {key: await self.process_value(value) for key, value in fn_kwargs.items()}
make this a gather and it'll then parallelize computation of dependencies?

2022-08-06 23:51 UTC, skrawcz commented on hamilton/driver.py
> +        return True  # We should just delegate to the superclass -- that should have a default implementation...
can just delete these.

2022-08-06 23:52 UTC, skrawcz commented on hamilton/driver.py
> +        self.coroutine_cache = {}  # Ughh python's coroutine API is terrible
good practice to call super().__init__() in the constructor

2022-08-07 00:03 UTC, skrawcz commented on hamilton/driver.py
> +    return {key: value for key, value in zip(keys, coroutines_gathered)}
```suggestion
    return dict(zip(keys, coroutines_gathered))
```

2022-08-07 19:39 UTC, elijahbenizzy commented on hamilton/driver.py
> +        return True  # We should just delegate to the superclass -- that should have a default implementation...
Nope as its abstract? That said, I changed it to inherit from the implemented one.

2022-08-07 19:42 UTC, elijahbenizzy commented
Remaining:
- [ ] Tests
- [ ] Determine how to release (experimental?)

2022-08-07 20:59 UTC, skrawcz commented on hamilton/experimental/h_async.py
> +        return self.result_builder.build_result(**outputs)
probably want to clear the cache here?

2022-08-07 21:05 UTC, skrawcz commented on examples/async/fastapi_example.py
> +    return await dr.raw_execute(['pipeline'], inputs=input_data)
hmm --right now if this is constructed per request, we're good -- things should be cleaned up and there'd be no memory leaks. However that incurs a penalty for each request.

But if we wanted to construct the driver once, then I think we'd get a memory leak? Also if multiple requests are sharing the same driver object & adapter, would anything weird happen 🤔 ?

2022-08-07 23:15 UTC, elijahbenizzy commented on hamilton/experimental/h_async.py
> +        return self.result_builder.build_result(**outputs)
Yeah, that's a great point

2022-08-07 23:16 UTC, elijahbenizzy commented on examples/async/fastapi_example.py
> +    return await dr.raw_execute(['pipeline'], inputs=input_data)
Yep, I think you're right here -- it could easily fill up. With multiple requests, it should be fine - they won't share the same set of coroutines. Even if they do (say you pass a coroutine in), the GIL assures parallelism works fine.

2022-08-07 23:17 UTC, elijahbenizzy commented on examples/async/fastapi_example.py
> +    return await dr.raw_execute(['pipeline'], inputs=input_data)
The problem is if we clear, it could break it, so we should really determine a run ID and clear for that run (as you said above)

2022-08-07 23:20 UTC, elijahbenizzy commented on examples/async/fastapi_example.py
> +    return await dr.raw_execute(['pipeline'], inputs=input_data)
I'd prefer to not have to manage this cache at all, as python should be able to do this, so I'm going to put this as a caveat for now, and see if I can get rid of this cache in the first place.

2022-08-08 04:52 UTC, skrawcz requested changes

2022-08-08 04:52 UTC, skrawcz commented on examples/async/README.md
> +2. Performance *should* be close to optimal but we have not benchmarked. We welcome contributions
```suggestion
2. Performance *should* be close to optimal but we have not benchmarked. We welcome contributions.
```

2022-08-08 04:52 UTC, skrawcz commented on examples/async/fastapi_example.py
> +            computation2))
We should probably not do this in an example. This doesn't feel very "ad hoc".

Otherwise 💡, fastapi could be a possible code compilation target too.

2022-08-08 04:52 UTC, skrawcz commented on hamilton/experimental/h_async.py
> +        @return: A coroutine
should this be task?

2022-08-08 04:52 UTC, skrawcz commented on hamilton/experimental/h_async.py
> +        @return: Whether the actual input value matches the type expected
we don't use this style :)
```suggestion
        :param node_type: Type of the input node, expected
        :param input_value: Type of the actual input, received
        :return: Whether the actual input value matches the type expected
```

2022-08-08 04:52 UTC, skrawcz commented on hamilton/experimental/h_async.py
> +    @return: The value (awaited if it is a coroutine, raw otherwise).
```suggestion
    :param val: Value to process.
    :return: The value (awaited if it is a coroutine, raw otherwise).
```

2022-08-08 04:52 UTC, skrawcz commented on hamilton/experimental/h_async.py
> +        @return: A coroutine
```suggestion
        :param node: Node to wrap
        :param kwargs: Keyword arguments (either coroutines or raw values) to call it with
        :return: A task
```

2022-08-08 04:52 UTC, skrawcz commented on hamilton/experimental/h_async.py
> +        @param result_builder: Results mixin to compile the graph's final results. TBD whether this should be included in the long run.
```suggestion
        :param config: Config to build the graph
        :param modules: Modules to crawl for fns/graph nodes
        :param result_builder: Results mixin to compile the graph's final results. TBD whether this should be included in the long run.
```

2022-08-08 04:52 UTC, skrawcz commented on hamilton/experimental/h_async.py
> +        @return: A dict of key -> result
```suggestion
        :param final_vars: Variables to execute (+ upstream)
        :param overrides: Overrides for nodes
        :param display_graph: whether or not to display graph -- this is not supported.
        :param inputs:  Inputs for DAG runtime calculation
        :return: A dict of key -> result
```

2022-08-08 04:52 UTC, skrawcz commented on hamilton/experimental/h_async.py
> +        return await await_dict_of_tasks({key: asyncio.create_task(process_value(memoized_computation[key])) for key in final_vars})
```suggestion
        task_dict = {key: asyncio.create_task(process_value(memoized_computation[key])) for key in final_vars}
        return await await_dict_of_tasks(task_dict)
```
Also is `process_value` needed here? Seems a bit redundant with the result being wrapped in a task and that awaited?

2022-08-08 04:52 UTC, skrawcz commented on examples/async/fastapi_example.py
> +    return {'computation1': computation1, 'computation2': computation2}
let's move these to a proper module.

2022-08-08 20:46 UTC, elijahbenizzy commented on hamilton/experimental/h_async.py
> +        @return: Whether the actual input value matches the type expected
Ughh need to update my pycharm to auto-correct to the right one

2022-08-08 20:48 UTC, elijahbenizzy commented on hamilton/experimental/h_async.py
> +        return await await_dict_of_tasks({key: asyncio.create_task(process_value(memoized_computation[key])) for key in final_vars})
`process_value` is needed but `create_task` is not I think...

2022-08-10 00:00 UTC, skrawcz commented on hamilton/experimental/h_async.py
> +        return await await_dict_of_tasks({key: asyncio.create_task(process_value(memoized_computation[key])) for key in final_vars})
okay. But this seems like an important line that should be at least two... break out the dict comprehension at least.

2022-08-10 00:02 UTC, skrawcz commented on hamilton/experimental/h_async.py
> +            fn_kwargs = await await_dict_of_tasks({key: process_value(value) for key, value in fn_kwargs.items()})
can move this dict comprehension to it's own line.

2022-08-10 00:03 UTC, skrawcz approved these changes
Just those two code nits, otherwise I think this looks good.

2022-08-10 01:02 UTC, merged