Adds Nullable validator
stitchfix/hamilton pull request #176
Opened 2022-08-10 20:47 UTC by elijahbenizzy

A few minor usabiility issues when I was messing with some Stitch Fix code.

## Changes
See commits.

## Testing

1.

## Notes

## Checklist

- [ ] PR has an informative and human-readable title (this will be pulled into the release notes)
- [ ] Changes are limited to a single goal (no scope creep)
- [ ] Code can be automatically merged (no conflicts)
- [ ] Code passed the pre-commit check & code is left cleaner/nicer than when first encountered.
- [ ] Passes all existing automated tests
- [ ] Any _change_ in functionality is tested
- [ ] New functions are documented (with a description, list of inputs, and expected output)
- [ ] Placeholder code is flagged / future TODOs are captured in comments
- [ ] Project documentation has been updated if adding/changing functionality.
- [ ] Reviewers requested with the [Reviewers tool](https://help.github.com/articles/requesting-a-pull-request-review/) :arrow_right:

## Testing checklist

### Python - local testing

- [ ] python 3.6
- [ ] python 3.7

2022-08-10 21:03 UTC, elijahbenizzy commented
This is very simple, happy to change names

2022-08-15 03:56 UTC, skrawcz requested changes

2022-08-15 03:56 UTC, skrawcz commented on hamilton/data_quality/default_validators.py
> +        self.allow_none = allow_none
The parameter name here is inconsistent with the class name; we want it to be obvious which validator maps to the kwarg. I.e. so either `no_nones_allowed` is the kwarg, or the class name is `AllowNoneValidatorAllTypes`.

2022-08-15 03:56 UTC, skrawcz commented on hamilton/graph.py
> +from hamilton.type_utils import custom_subclass_check
inconsistent with our style.

This should be `from hamilton import type_utils` -- and then where the function is used, prefixed with the module.

2022-08-15 04:43 UTC, elijahbenizzy commented on hamilton/graph.py
> +from hamilton.type_utils import custom_subclass_check
We need an automated checker...

2022-08-15 04:52 UTC, elijahbenizzy commented on hamilton/data_quality/default_validators.py
> +        self.allow_none = allow_none
Sure, although I'm not sure there's value in consistency over self-description here.

2022-08-15 04:53 UTC, elijahbenizzy commented on hamilton/data_quality/default_validators.py
> +        self.allow_none = allow_none
Sure, although I'm not sure there's value in consistency over self-description here.

2022-08-15 15:49 UTC, skrawcz approved these changes
you going to squash merge with a nice commit?

2022-08-15 15:54 UTC, elijahbenizzy commented
> you going to squash merge with a nice commit?

Going to quickly consolidate into two commits

> you going to squash merge with a nice commit?

Nope I'll turn this into two commits then commit them both -- should have been two PRs

2022-08-15 16:04 UTC, merged