Fixes bug for @does working with optional dependencies #185
stitchfix/hamilton pull request #187
Opened 2022-08-22 23:58 UTC by elijahbenizzy

Need to add a few more pieces to make this work -- this is a WIP.

[Short description explaining the high-level reason for the pull request]

## Changes

-

## Testing

1.

## Notes

## Checklist

- [ ] PR has an informative and human-readable title (this will be pulled into the release notes)
- [ ] Changes are limited to a single goal (no scope creep)
- [ ] Code can be automatically merged (no conflicts)
- [ ] Code passed the pre-commit check & code is left cleaner/nicer than when first encountered.
- [ ] Passes all existing automated tests
- [ ] Any _change_ in functionality is tested
- [ ] New functions are documented (with a description, list of inputs, and expected output)
- [ ] Placeholder code is flagged / future TODOs are captured in comments
- [ ] Project documentation has been updated if adding/changing functionality.
- [ ] Reviewers requested with the [Reviewers tool](https://help.github.com/articles/requesting-a-pull-request-review/) :arrow_right:

## Testing checklist

### Python - local testing

- [ ] python 3.6
- [ ] python 3.7

2022-08-26 04:20 UTC, elijahbenizzy commented
Ughh this took longer than I want but I want to add the ability to have it work with `*args`. That said, i think this is good enough for now and I want some more user feedback before investing further.

2022-08-26 21:46 UTC, skrawcz commented
@elijahbenizzy guess we need to fix the ray workflow API... seems like it changed.

2022-08-26 21:50 UTC, skrawcz reviewed
haven't finished look at code just yet -- but found doc string issues.

2022-08-26 21:50 UTC, skrawcz commented on decorators.md
> +replace any function.
what do you mean replace any function?

2022-08-26 21:50 UTC, skrawcz commented on decorators.md
> +    """This function takes any number of inputs and sums them all together."""
fix doc string

2022-08-26 21:50 UTC, skrawcz commented on decorators.md
> +    """Adds D_XMAS_GC_WEIGHTED_BY_DAY_1 and D_XMAS_GC_WEIGHTED_BY_DAY_2"""
doc string

2022-08-26 21:50 UTC, skrawcz commented on decorators.md
> +    """Adds D_XMAS_GC_WEIGHTED_BY_DAY_1 and D_XMAS_GC_WEIGHTED_BY_DAY_2"""
doc string

2022-08-26 21:50 UTC, skrawcz commented on decorators.md
> +In the above example, `@does` applies our internal function `_load_data`, which applies icustomer
typo

2022-08-26 21:50 UTC, skrawcz commented on hamilton/dev_utils/deprecation.py
> +        :paramfn: function (or class) to decorate
`:param fn:`

2022-08-26 21:50 UTC, skrawcz commented on hamilton/function_modifiers.py
> +    :paramliteral_value: Python literal value to use
missing whitespace

2022-08-26 21:50 UTC, skrawcz commented on hamilton/function_modifiers.py
> +    :paramdependency_on: Upstream node to come from
missing whitespace

2022-08-26 21:50 UTC, skrawcz commented on hamilton/function_modifiers.py
> +        :paramparametrization: **kwargs with one of two things:
missing whitespace

2022-08-26 21:50 UTC, skrawcz commented on hamilton/function_modifiers.py
> +    :return:An UpstreamDependency object -- a signifier to the internal framework of the dependency type.
missing whitespace

2022-08-27 03:37 UTC, skrawcz requested changes

2022-08-27 03:37 UTC, skrawcz commented on hamilton/function_modifiers.py
> +    def __init__(self, replacing_function: Callable, **argument_mapping: Union[str, List[str]]):
`None` default for compatibility?

2022-08-27 03:37 UTC, skrawcz commented on hamilton/function_modifiers.py
> +    def ensure_output_types_match(fn: Callable, replace_with: Callable):
this would be clearer I think?
```suggestion
    def ensure_output_types_match(og_function: Callable, replacement_function: Callable):
```

2022-08-27 03:37 UTC, skrawcz commented on hamilton/function_modifiers.py
> +        annotation_todo = inspect.signature(replace_with).return_annotation
should change `annotation_todo` here too

2022-08-27 03:37 UTC, skrawcz commented on hamilton/function_modifiers.py
> +        fn: Callable, replace_with: Callable, argument_mapping: Dict[str, str]
og_function and replacement_function suggestion hold here too.

2022-08-27 03:37 UTC, skrawcz commented on hamilton/function_modifiers.py
> +                    invalid_fn_parameters.append(param_name)
`_two_params`?

2022-08-27 03:37 UTC, skrawcz commented on hamilton/function_modifiers.py
> +        does.ensure_function_signature_compatible(
why not self?

2022-08-27 03:37 UTC, skrawcz commented on hamilton/function_modifiers.py
> +        and the same parameters/types as
unfinished sentence?

2022-08-28 21:31 UTC, elijahbenizzy commented on hamilton/function_modifiers.py
> +    :paramliteral_value: Python literal value to use
Ughh these were a bad find and replace to fix all the `@` my IDE keeps wanting to leave in.

2022-08-28 21:32 UTC, elijahbenizzy commented on hamilton/function_modifiers.py
> +    def __init__(self, replacing_function: Callable, **argument_mapping: Union[str, List[str]]):
No, argument_mapping is a `**kwarg` so if you don't pass in any kwargs it'll be an empty dict.

2022-08-28 21:38 UTC, elijahbenizzy commented on hamilton/function_modifiers.py
> +        does.ensure_function_signature_compatible(
Static method -- should be called statically. Otherwise people will end up calling it and overriding it as a non-static method.

2022-08-29 04:04 UTC, skrawcz commented on hamilton/function_modifiers.py
> +        does.ensure_function_signature_compatible(
got it... TIL about python.

2022-08-30 03:57 UTC, skrawcz approved these changes

2022-08-30 03:57 UTC, skrawcz commented on decorators.md
> +functions.
```suggestion
2. `**argument_mapping` -- a mapping of arguments from the replacing function to the replacing function. This makes for easy reuse of
functions. Confused? See the examples below.
```

2022-08-30 04:05 UTC, merged