Adding container image for running examples
stitchfix/hamilton pull request #209
Opened 2022-10-13 15:10 UTC by bovem

Added dockerfile for testing examples in a container environment.

## Changes

- Added a dockerfile for the image that could be used for running examples.
- Each example folder has a python virtual environment named `hamilton` that should be activated first before running the example.

## Testing

- Build the container image
```bash
docker build --tag hamilton-example .
```

- Creating a container
```bash
docker run -it --rm --name hamilton-example hamilton-example
```

- Running the `hello_world` example inside the container
```bash
cd hamilton/example/hello_world
source hamilton-env/bin/activate
python my_script.py
```

## Notes

## Checklist

- [x] PR has an informative and human-readable title (this will be pulled into the release notes)
- [x] Changes are limited to a single goal (no scope creep)
- [x] Code can be automatically merged (no conflicts)
- [x] Code passed the pre-commit check & code is left cleaner/nicer than when first encountered.
- [ ] Passes all existing automated tests
- [ ] Any _change_ in functionality is tested
- [x] New functions are documented (with a description, list of inputs, and expected output)
- [ ] Placeholder code is flagged / future TODOs are captured in comments
- [x] Project documentation has been updated if adding/changing functionality.
- [ ] Reviewers requested with the [Reviewers tool](https://help.github.com/articles/requesting-a-pull-request-review/) :arrow_right:

## Testing checklist

### Python - local testing

- [ ] python 3.6
- [ ] python 3.7
- [x] python 3.9 (Docker Environment)

2022-10-14 17:48 UTC, skrawcz requested changes
Just two minor comments, otherwise I ran things and everything worked as specified! Once you have addressed those, this is good to merge. Thanks!

2022-10-14 17:48 UTC, skrawcz commented on examples/README.md
> +3. Creating a container
```suggestion
3. Starting your docker container
```

2022-10-14 17:48 UTC, skrawcz commented on examples/README.md
> +python my_script.py
```suggestion
python my_script.py
deactivate  # this will exit the python virtual environment once you don't need it.
```

2022-10-14 17:48 UTC, skrawcz commented on examples/README.md
> +source hamilton-env/bin/activate
```suggestion
source hamilton-env/bin/activate # this will activate the virtual environment
```

2022-10-14 17:48 UTC, skrawcz commented on examples/README.md
> +```
Can you add something like:

You should be able to run all the examples that have *only* a `requirements.txt`. If there are other requirements.txt files (like under data_quality), you'll just need to manually create an environment and install those requirements yourself.

2022-10-14 18:01 UTC, skrawcz approved these changes
Actually you know what, I'll just merge this as is -- since it's just documentation that I'm wanting updates to,  I can go ahead and update that after merging and save you the trouble of doing it.

Thanks for your contribution!

![image](https://media4.giphy.com/media/osjgQPWRx3cac/giphy.gif)

2022-10-14 18:01 UTC, merged

2022-10-15 14:12 UTC, bovem commented
Thanks @skrawcz it was fun to work on this issue. I'll keep looking on open issues to see if I could contribute on something else.