Python 3 11 support
stitchfix/hamilton pull request #291
Opened 2023-01-29 20:05 UTC by elijahbenizzy

[Short description explaining the high-level reason for the pull request]

## Changes

## How I tested this

## Notes

## Checklist

- [ ] PR has an informative and human-readable title (this will be pulled into the release notes)
- [ ] Changes are limited to a single goal (no scope creep)
- [ ] Code passed the pre-commit check & code is left cleaner/nicer than when first encountered.
- [ ] Any _change_ in functionality is tested
- [ ] New functions are documented (with a description, list of inputs, and expected output)
- [ ] Placeholder code is flagged / future TODOs are captured in comments
- [ ] Project documentation has been updated if adding/changing functionality.

2023-01-29 20:18 UTC, elijahbenizzy commented
Removed tests, decided not to make it impossible to install as I don't want to create a new major version. Next major version release will probably be. 3.8 or 3.10 +.

2023-01-29 21:40 UTC, skrawcz requested changes
I don't see how this fulfills requirements for 3.11 and removing 3.6

1. can the 3.6 commit be separate please?
2. I think there's a few changes that are missing:
* setup.py is not modified.
* requirements.txt isn't updated
* references to 3.6 python aren't removed -- line 79 in hamilton/base.py, line 91 in test_h_async.py

2023-01-29 21:40 UTC, skrawcz commented on .circleci/config.yml
> +      - image: cimg/python:<< parameters.python-version >>
?

2023-01-29 23:01 UTC, elijahbenizzy commented
> I don't see how this fulfills requirements for 3.11 and removing 3.6
> 
> 1. can the 3.6 commit be separate please?
> 2. I think there's a few changes that are missing:
> 
> * setup.py is not modified.
> * requirements.txt isn't updated
> * references to 3.6 python aren't removed -- line 79 in hamilton/base.py, line 91 in test_h_async.py

Can split out commits. See https://github.com/stitchfix/hamilton/pull/291#issuecomment-1407760328 for why I didn't *fully* remove 3.6 support. I think we'd have to cut a major version or break the semantic versioning rules. I guess we could cut a minor one...

2023-01-29 23:01 UTC, elijahbenizzy commented on .circleci/config.yml
> +      - image: cimg/python:<< parameters.python-version >>
This worked, the other one didn't :)

2023-01-30 02:29 UTC, elijahbenizzy commented
Think I got everything

2023-01-30 05:53 UTC, skrawcz commented
> > I don't see how this fulfills requirements for 3.11 and removing 3.6
> > 
> > 1. can the 3.6 commit be separate please?
> > 2. I think there's a few changes that are missing:
> > 
> > 
> > * setup.py is not modified.
> > * requirements.txt isn't updated
> > * references to 3.6 python aren't removed -- line 79 in hamilton/base.py, line 91 in test_h_async.py
> 
> Can split out commits. See [#291 (comment)](https://github.com/stitchfix/hamilton/pull/291#issuecomment-1407760328) for why I didn't _fully_ remove 3.6 support. I think we'd have to cut a major version or break the semantic versioning rules. I guess we could cut a minor one...

As discussed. I think we're fine. Python 3.6 people just wont get new updates -- so no broken functionality for them.

2023-01-30 05:53 UTC, skrawcz commented
@elijahbenizzy just requirements.txt -- doesn't need dataclasses conditional install anymore

2023-01-30 17:06 UTC, skrawcz approved these changes

2023-01-30 17:11 UTC, merged