modified hardcoded links in docs
stitchfix/hamilton pull request #309
Opened 2023-02-13 17:25 UTC by CharityKithaka

[Modified hardcoded links to follow the rSt way of writing.]

## Changes
Changed all links in all the docs. 

## Checklist

- [ ] PR has an informative and human-readable title (this will be pulled into the release notes)
- [ ] Changes are limited to a single goal (no scope creep)
- [ ] Any _change_ in functionality is tested
- [ ] New functions are documented (with a description, list of inputs, and expected output)
- [ ] Placeholder code is flagged / future TODOs are captured in comments
- [ ] Project documentation has been updated if adding/changing functionality.

2023-02-13 17:51 UTC, CharityKithaka commented
Hey @skrawcz the changes.

2023-02-14 05:21 UTC, skrawcz requested changes
Thanks for the touch ups! But a couple of things to fix up please.

1. Removing the vscode file.
2. There was a paragraph that I think you by accident deleted some words from.
3. The reST guide has a `trailing slash` i.e. `/` in its example. We don't actually need that trailing slash `/` for our links. Could you remove it for the links that you added it to please?
e.g. `<https://medium.com/avmconsulting-blog/running-a-python-application-on-kubernetes-aws-56609e7cd88c/>`_ should just be `<https://medium.com/avmconsulting-blog/running-a-python-application-on-kubernetes-aws-56609e7cd88c>`_

2023-02-14 05:21 UTC, skrawcz commented on .vscode/settings.json
> +}
please remove this file.

2023-02-14 05:21 UTC, skrawcz commented on docs/extensions.rst
> +What this doesn't help with is data scale, as you're still limited to what fits in memory on your mach
revert this change please.

2023-02-14 05:21 UTC, skrawcz commented on docs/hamilton-community.rst
> +Slack space name: `slack community <https://hamilton-opensource.slack.com/>`_
```suggestion
Slack space name: `hamilton-opensource <https://hamilton-opensource.slack.com/>`_
```

2023-02-14 05:21 UTC, skrawcz commented on docs/hamilton-community.rst
> +Slack invite link: `slack link <https://join.slack.com/t/hamilton-opensource/shared\_invite/zt-1bjs72asx-wcUTgH7q7QX1igiQ5bbdcg/>`_
```suggestion
Slack invite link: `click me to join! <https://join.slack.com/t/hamilton-opensource/shared\_invite/zt-1bjs72asx-wcUTgH7q7QX1igiQ5bbdcg>`_
```

2023-02-14 05:21 UTC, skrawcz commented on docs/hamilton-community.rst
> +Slack space name: `slack community <https://hamilton-opensource.slack.com/>`_
Just suggesting some better wording here.

2023-02-14 05:22 UTC, skrawcz commented on docs/hamilton-community.rst
> +Slack invite link: `slack link <https://join.slack.com/t/hamilton-opensource/shared\_invite/zt-1bjs72asx-wcUTgH7q7QX1igiQ5bbdcg/>`_
Just suggesting some better wording here.

2023-02-14 11:14 UTC, CharityKithaka commented
hey @skrawcz worked on the changes.

2023-02-15 05:48 UTC, skrawcz commented
@CharityKithaka the pre-commit check is failing. Could you:

1. install pre-commit. `pre-commit install`
2. run it -- `pre-commit run --all-files` -- it should fix the two files that are failing.
3. commit the changes.
If you need help see https://github.com/stitchfix/hamilton/blob/main/developer_setup.md#set-up-your-local-dev-environment and https://pre-commit.com/

2023-02-15 10:55 UTC, CharityKithaka commented
Hey @skrawcz everything is in order now.

2023-02-15 19:37 UTC, skrawcz approved these changes
Thanks @CharityKithaka! I will merge this now. Sorry I have been a little swamped this week; I will try to get you another task tomorrow/the day after.

2023-02-15 19:39 UTC, merged

2023-02-15 20:00 UTC, CharityKithaka commented
Hey, @skrawcz that would be great. I will truly appreciate it.